server:
  port: 80
  servlet:
    context-path: /cryptolalia

mybatis:
  mapper-locations: classpath:mapper/**/*
  type-aliases-package: com.wy.cryptolalia.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cryptolaliaDB?serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  redis:
    host: 
    password:
    port: 6379
logging:
  level.com.wy.cryptolalia: debug

